"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['StatusPageMonitor.py']
DATA_FILES = [
    ('icons', [
        'icons/check-mark-button.png',
        'icons/collision.png',
        'icons/exclamation-mark.png',
        'icons/warning.png'
    ])
]
OPTIONS = {}

setup(
    name='StatusPage Monitor',
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    install_requires=[
        'rumps',
        'requests'
    ],
    setup_requires=['py2app'],
)
